### ISSUE TITLE
MSTDtcAnomL2 weight?

### ISSUE THREAD

**Issue by xarryon** [MekAkUActOR/DAFAR-Prototype#1]
thx for this great work! Could u please tell how to get the MSTDtcAnomL2 weights as this weight is very useful to generate threshold. Does the weight is generated by reconsitution for input?

**Comment by MekAkUActOR** [comment]
Sorry for the late response. Yes you can train the decoder with self-supervised manner (as in the manuscript). L2 in the model name means using l2 reconstruction loss. And I believe the model is also stored in https://github.com/MekAkUActOR/DAFAR-Prototype/blob/main/utils/model/DETECTOR/MSTDtcAnomL2.pth.

But please note that this technique may be already out-dated for adversarial example research. For good defense methods with theoretical guarantee, I recommend you to research on certified training. Please refer to https://www.sri.inf.ethz.ch/teaching/rtai22 for SOTA technologies in this field.
